config/routes.rb
Rails.application.routes.draw do

  get root :to => 'homes#top'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :books
  patch '/books/:id' => 'books#update', as: 'up_book'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
 validates :title, presence: true
 validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def create
    @book = Book.new(list_params)
    if @book.save
      flash[:notice] = "Book was successfully created."
      redirect_to book_path(@book)
    else
      @books = Book.all
      render :index
    end
  end

  def index
    @book = Book.new
    @books = Book.all
  end

  def show
    @data = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id]) #データベースから一つだけ取得
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(list_params)
      redirect_to book_path(@book.id)
      flash[:notice] = "Book was successfully updated."
    else
      @books = Book.all
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    flash[:notice] = "Book was successfully destroyed."

    redirect_to '/books'
  end

  private
    def list_params
      params.require(:book).permit(:title, :body)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<body>

    <h1>Editing Book</h1>

    <% if @book.errors.any? %>
        <div id="error_explanation">
            <h3>
                <%= @book.errors.count %> errors prohibited this book from being saved:
            </h3>
            <ul>
                <% @book.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
            </ul>
        </div>

        <div class="forms">
            <%= form_with model: @book, url: up_book_path(@book.id), method: :patch do |f| %> <!--updateアクションにデータ送る-->
                <div class="form">
                    <div class="field_with_errors">
                        <label>Title</label>
                    </div>
                    <%= f.text_field :title %>
                </div>
                <div class="form">
                    <div class="field_with_errors">
                        <label>Body</label>
                    </div>
                    <%= f.text_area :body %>
                </div>
                <div class="actions">
                    <input type="submit" value="Update Book" class="btn">
                </div>
            <% end %>
        </div>


    <% else %>


        <div class="forms">
            <%= form_with model: @book, url: up_book_path(@book.id), method: :patch do |f| %> <!--updateアクションにデータ送る-->
                <div class="form">
                    <label>Title</label>
                    <%= f.text_field :title %>
                </div>
                <div class="form">
                    <label>Body</label>
                    <%= f.text_area :body %>
                </div>
                <div class="actions">
                    <input type="submit" name="commit" value="Update Book" data-disable-with="Update Book"class="btn">
                </div>
            <% end %>
        </div>

    <% end %>

        <span><%= link_to "Show", "/books/#{@book.id}", class: "link" %></span>
        <span>|</span>
        <span><%= link_to "Back", "/books", class: "link" %></span>



</body>

app/views/books/index.html.erb
<body>

<% if flash[:notice] %>
     <p id="notice">
       <%= flash[:notice] %>
     </p>
<% end %>

<!--ここから下は一覧テーブルだよ-->
  <h1>Books</h1>


<table>
   <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3">本当は空だよ</th>
    </tr>
   <% @books.each do |book| %>
    <tbody>
      <td><span><%= book.title %></span></td>
      <td><span><%= book.body %></span></td>
      <td>
        <%= link_to "Show", "/books/#{book.id}", class: "link" %>
      </td>
      <td>
        <%= link_to "Edit", "/books/#{book.id}/edit",class: "link" %>
      </td>
      <td>
        <%= link_to "Destroy","/books/#{book.id}", method: :delete, "data-confirm" => "Are you sure?", class: "link" %>
      </td>
    </tbody>

   <% end %>

</table>

<!-- ここから下は投稿フォームだよ-->

  <h2>New book</h2>

  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h3>
        <%= @book.errors.count %>　errors prohibited this book from being saved:
      </h3>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>

    <div class="forms">
      <%= form_with model: @book, url: '/books', method: :post do |f| %>
        <div class="form">
          <div class="field_with_errors">
            <label>Title</label>
          </div>
          <%= f.text_field :title %>
        </div>
        <div class="form">
          <div class="field_with_errors">
            <label>Body</label>
          </div>
          <%= f.text_area :body %>
        </div>
        <input type="submit"  name="commit" value="Create Book" class="btn">
      <% end %>
    </div>

  <% else %>
    <div class="forms">
        <%= form_with model: @book, url: '/books', method: :post do |f| %>
          <div class="form">
            <label>Title</label>
            <%= f.text_field :title %>
          </div>
          <div class="form">
            <label>Body</label>
            <%= f.text_area :body %>
          </div>
          <input type="submit" name="commit" value="Create Book" data-disable-with="Create Book" class="btn">
        <% end %>
    </div>
  <% end %>




  <!--↑ここまでエラー処理-->

<!--新規投稿をここに記入-->


</body>

app/views/books/show.html.erb
<body>
  <!--サクセスメッセージ-->
  <% if flash[:notice] %>
     <p id="notice">
       <%= flash[:notice] %>
     </p>
  <% end %>

  <p>
    <strong>Title: </strong>
    <%= @data.title %>
  </p>


  <p>
    <strong>Body: </strong>
    <%= @data.body %>
  </p>



  <span><%= link_to "Edit", "/books/#{@data.id}/edit", class: "link" %></span>
  <span>|</span>
  <span><%= link_to "Back", "/books", class: "link" %></span>
</body>

app/views/homes/top.html.erb
<body>
    <h1>ようこそ<span class="st"> Bookers </span>へ！</h1>
    <p><span class="st">Bookers</span> では、さまざまな書籍に関するあなたの意見や</p>
    <p>印象を共有し交換することができます</p>
    <p><a href="/books" class="link">start</a></p>

</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  

  <body>
    <%= yield %>
  </body>
</html>